import networkx as nx


class PrettyPrinter:
    """
    Traverse the parameter graph and prints all the value attribute of the nodes where the class_
    attribute is ``TerminalNodeImpl``.
    """
    def __init__(self, g: nx.DiGraph):
        self._graph = g
        self._script = ""

    @property
    def get_script(self):
        """
        Returns the script generated by the traversal of the graph.

        The script is a string where each line corresponds to a node of the graph.
        The content of the node is added to the script if the node is of class_
        ``TerminalNodeImpl``. The content is added if it is not None.

        Returns:
            str: The script generated by the traversal of the graph.
        """
        self._traverse(list(self._graph.nodes)[0])
        return self._script

    def _traverse(self, node):
        """
        This method traverses the graph starting from the given node and prints the value
        attribute of the visited nodes. The node is visited if its class_ attribute is
        ``TerminalNodeImpl`` and its value attribute is not None.

        Args:
            node (int): The node to start the traversal from.
        """
        node_value = self._graph.nodes[node]['value']
        if node_value is not None:
            try:
                if ';' in node_value or '{' in node_value or "\\}" in node_value:
                    self._script += node_value + '\n'
                elif self._script[-1] == '.' or self._script[-1] == ' ' or node_value == '.':
                    self._script += node_value
                else:
                    self._script += ' ' + node_value
            except IndexError:
                self._script += node_value
        else:
            try:
                for child in self._graph.successors(node):
                    self._traverse(child)
            except Exception as e:
                print(e)
